version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./config.d:/mnt/config
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config.d:/mnt/config
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    env_file:
      - ./config
    networks:
      - loki
